describe('empty spec', () => {
  const newListName = "New Todo List (autogenerated)" + new Date().getTime();
  let newListID = "";

  beforeEach(() => {
    cy.visit('http://localhost:3000')

  })

  after(() => {
    cy.get("#__next > div > header > div > button[aria-label=\"delete\"]")
    .click();
  });

  it('create a new todo list', () => {

    cy.get("#__next > div > div > div > nav > button").click();

    cy.get("#new-todo-list").type(newListName);

    cy.get("body > div.MuiModal-root.css-79ws1d-MuiModal-root > div.MuiBox-root.css-1wnsr1i > form > button").click();

    cy.get("#__next > div > div > div > nav")
      .children()
      .contains(newListName);
  })

  it('create new todo item in list', () => {

    cy.get("#__next > div > div > div > nav")
      .children()
      .contains(newListName).click();
    
    const inputForm = cy.get("#__next > div > main > div > div > div > form");

    let i = 0;
    while (i < 5) {
      cy.get("#__next > div > main > div > div > div > form > span > div > div > input")
      .type('Todo Item' + new Date().getTime() )
      inputForm.submit()
      i++;
      cy.wait(600);
    }
    

  })

  it('check all items in list', () => {

    cy.get("#__next > div > div > div > nav")
      .children()
      .contains(newListName).click();

    cy.wait(1000);

    cy.get("#__next > div > main > div > div > div > span > span > input").each((element) => {
        element.trigger("click");
    });
      
  })

  it('add more items to list', () => {

  cy.get("#__next > div > div > div > nav")
      .children()
      .contains(newListName).click();
    
    const inputForm = cy.get("#__next > div > main > div > div > div > form");

    let i = 0;
    while (i < 5) {
      cy.get("#__next > div > main > div > div > div > form > span > div > div > input")
      .type('New Todo Item' + new Date().getTime() )
      inputForm.submit()
      i++;
      cy.wait(600);
    }

  })

  it('delete all checked items in list', () => {
    cy.get("#__next > div > div > div > nav")
    .children()
    .contains(newListName).click();

    cy.wait(500);

    cy.get("#__next > div > main > div > div > div > span > span > input:checked").each((element) => {
      const deleteButton = element.parent().parent().next().next().children().first();

      deleteButton.trigger('click');
      
    });
  })

})

export {}